import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { 
		MatTabsModule,
		MatSidenavModule,
		MatToolbarModule,
		MatIconModule,
		MatButtonModule,
		MatListModule,
		MatInputModule,
		MatProgressSpinnerModule,
		MatDialogModule,
		MatCardModule,
		MatSelectModule,
		MatSnackBarModule,
		MatTableModule,
		MatPaginatorModule,
		MatSortModule,
		MatProgressBarModule,
		MatExpansionModule,
		MatDatepickerModule,
		MatNativeDateModule,
		MatCheckboxModule,
		MatAutocompleteModule,
		MatTooltipModule,
		MatTreeModule,
		MatStepperModule,
		MatMenuModule,
	   } from '@angular/material';

import { MatRadioModule } from '@angular/material/radio';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
	MatTabsModule,
    MatSidenavModule,
	MatToolbarModule,
	MatIconModule,
	MatButtonModule,
	MatListModule,
	MatInputModule,
	MatProgressSpinnerModule,
	MatDialogModule, 
	MatCardModule,
	MatSelectModule,
	MatSnackBarModule,
	MatTableModule,
	MatPaginatorModule,
	MatSortModule,
	MatProgressBarModule,
	MatExpansionModule,
	MatDatepickerModule,
	MatNativeDateModule,
	MatCheckboxModule,
	MatAutocompleteModule,
	MatTooltipModule,
	MatTreeModule,
	MatStepperModule,
	MatRadioModule,
	MatMenuModule,
  ],
  exports: [
    MatTabsModule,
    MatSidenavModule,
	MatToolbarModule,
	MatIconModule,
	MatButtonModule,
	MatListModule,
	MatInputModule,
	MatProgressSpinnerModule,
	MatDialogModule, 
	MatCardModule,
	MatSelectModule,
	MatSnackBarModule,
	MatTableModule,
	MatPaginatorModule,
	MatSortModule,
	MatProgressBarModule,
	MatExpansionModule,
	MatDatepickerModule,
	MatNativeDateModule,
	MatCheckboxModule,
	MatAutocompleteModule,
	MatTooltipModule,
	MatTreeModule,
	MatStepperModule,
	MatRadioModule,
	MatMenuModule,
  ],
})
export class MaterialModule { }
